name: campus_ease
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  firebase: ^9.0.3
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.4
  freezed_annotation: ^2.4.1
  http: ^0.13.6
  json_annotation: ^4.8.1
  loading_indicator: ^3.1.1
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  supabase_flutter: ^1.10.25
  url_launcher_windows: ^3.1.1

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  freezed: ^2.5.2
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/